language: node_js


node_js:
- '0.12'


before_install:
- npm install hexo -g

# config for `hexo deploy`
- openssl aes-256-cbc -K $encrypted_4dbc5423f685_key -iv $encrypted_4dbc5423f685_iv
  -in .travis/travis_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "travis_bot"
- git config --global user.email "mithvv@gmail.com"


script:
- hexo generate
- hexo deploy


branches:
  only:
  - blog
